name: Build Windows Executables

on:
  push:
    branches: [ ci ] # change this to windows when ready

jobs:
  ci:
    name: Test and Package (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # update with your targeted Python version

      - name: Install Briefcase
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install briefcase

      - name: Build App
        run: |
          briefcase build windows app --test --no-input --log

      - name: Package App
        run: |
          briefcase package windows app --update --adhoc-sign --no-input --log

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: windows_ann_haliszt
          path: dist
          if-no-files-found: error

      - name: Upload Log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Log-Failure-Windows
          path: logs/*